#pragma once

static const char kLightVertexSource[] =
    "uniform mat4 u_model_view_projection;\n"
    "\n"
    "attribute vec3 a_position;\n"
    "attribute vec4 a_texture_coordinates;\n"
    "\n"
    "varying vec2 v_texture_coordinates;\n"
    "varying vec3 v_world_position;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    v_texture_coordinates = a_texture_coordinates.xy;\n"
    "    v_world_position      = a_position;\n"
    "\n"
    "    gl_Position = u_model_view_projection * vec4(a_position, 1.0);\n"
    "}\n"
    ;

static const char kLightFragmentSource[] =
    "uniform sampler2D u_surface_texture;\n"
    "uniform sampler2D u_light_texture;\n"
    "\n"
    "uniform float u_surface_mode;\n"
    "uniform float u_alpha;\n"
    "uniform float u_alpha_test;\n"
    "\n"
    "uniform vec4 u_surface_normal;\n"
    "uniform float u_normal_horizontal;\n"
    "\n"
    "uniform int  u_light_count;\n"
    "uniform vec4 u_light_position_radius[4];\n"
    "uniform vec4 u_light_color[4];\n"
    "\n"
    "varying vec2 v_texture_coordinates;\n"
    "varying vec3 v_world_position;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 surface = texture2D(u_surface_texture, v_texture_coordinates);\n"
    "\n"
    "    vec4 base;\n"
    "\n"
    "    if (u_surface_mode < 0.5)\n"
    "        base = surface;\n"
    "    else if (u_surface_mode < 1.5)\n"
    "        base = vec4(1.0, 1.0, 1.0, 1.0);\n"
    "    else\n"
    "        base = vec4(1.0, 1.0, 1.0, surface.a);\n"
    "\n"
    "    vec3 accumulated = vec3(0.0, 0.0, 0.0);\n"
    "\n"
    "    for (int index = 0; index < 4; index++)\n"
    "    {\n"
    "        if (index >= u_light_count)\n"
    "            break;\n"
    "\n"
    "        vec3  delta  = v_world_position - u_light_position_radius[index].xyz;\n"
    "        float radius = u_light_position_radius[index].w;\n"
    "\n"
    "        vec2  light_coordinates;\n"
    "        float plane_distance;\n"
    "\n"
    "        if (u_normal_horizontal > 0.5)\n"
    "        {\n"
    "            light_coordinates = vec2((1.0 + delta.x / radius) * 0.5, (1.0 + delta.y / radius) * 0.5);\n"
    "\n"
    "            plane_distance = abs(delta.z) / radius;\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            float scaled_radius = radius / u_surface_normal.w;\n"
    "\n"
    "            float tangent = u_surface_normal.x * delta.y - u_surface_normal.y * delta.x;\n"
    "\n"
    "            light_coordinates =\n"
    "                vec2((1.0 + tangent / scaled_radius) * 0.5, (1.0 + delta.z / scaled_radius) * 0.5);\n"
    "\n"
    "            plane_distance = abs(dot(u_surface_normal.xyz, delta)) / scaled_radius;\n"
    "        }\n"
    "\n"
    "        float intensity = exp(-5.44 * plane_distance * plane_distance);\n"
    "\n"
    "        accumulated += u_light_color[index].rgb * intensity * texture2D(u_light_texture, light_coordinates).rgb;\n"
    "    }\n"
    "\n"
    "    float output_alpha = base.a * u_alpha;\n"
    "\n"
    "    if (output_alpha < u_alpha_test)\n"
    "        discard;\n"
    "\n"
    "    gl_FragColor = vec4(base.rgb * accumulated, output_alpha);\n"
    "}\n"
    ;

