#pragma once

static const char kModelVertexSource[] =
    "uniform mat4 u_model_view_projection;\n"
    "uniform mat4 u_model_view;\n"
    "uniform mat4 u_model_transform;\n"
    "\n"
    "uniform float u_lerp;\n"
    "\n"
    "uniform vec2 u_texture_scale;\n"
    "uniform vec2 u_texture_offset;\n"
    "\n"
    "attribute vec3 a_position_frame1;\n"
    "attribute vec3 a_position_frame2;\n"
    "attribute vec2 a_texture_coordinates;\n"
    "attribute vec3 a_color;\n"
    "attribute vec3 a_normal_frame1;\n"
    "attribute vec3 a_normal_frame2;\n"
    "\n"
    "varying vec4 v_color_and_u;\n"
    "varying vec4 v_eye_and_v;\n"
    "varying vec3 v_normal;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec3 blended = mix(a_position_frame1, a_position_frame2, u_lerp);\n"
    "\n"
    "    vec4 model_position = u_model_transform * vec4(blended, 1.0);\n"
    "\n"
    "    vec2 texture_coordinates = a_texture_coordinates * u_texture_scale + u_texture_offset;\n"
    "\n"
    "    vec3 blended_normal = mix(a_normal_frame1, a_normal_frame2, u_lerp);\n"
    "\n"
    "    vec3 model_normal = mat3(u_model_transform[0].xyz, u_model_transform[1].xyz, u_model_transform[2].xyz) *\n"
    "                        blended_normal;\n"
    "\n"
    "    v_color_and_u = vec4(a_color, texture_coordinates.x);\n"
    "    v_eye_and_v   = vec4((u_model_view * model_position).xyz, texture_coordinates.y);\n"
    "    v_normal      = normalize(mat3(u_model_view[0].xyz, u_model_view[1].xyz, u_model_view[2].xyz) * model_normal);\n"
    "\n"
    "    gl_Position = u_model_view_projection * model_position;\n"
    "}\n"
    ;

static const char kModelFragmentSource[] =
    "const float kFogLinear = 1.0;\n"
    "const float kLog2      = 1.442695;\n"
    "\n"
    "uniform sampler2D u_texture0;\n"
    "\n"
    "uniform sampler2D u_light_data;\n"
    "uniform sampler2D u_light_headers;\n"
    "uniform sampler2D u_light_indices;\n"
    "\n"
    "uniform float u_world_lit;\n"
    "uniform vec4  u_light_view;\n"
    "uniform vec4  u_light_list;\n"
    "uniform vec3  u_light_bounds_min;\n"
    "uniform vec3  u_light_bounds_range;\n"
    "uniform float u_light_radius_scale;\n"
    "uniform float u_light_data_step;\n"
    "\n"
    "uniform float u_glow_count;\n"
    "uniform vec4  u_glow_plane[EDGE_LIGHT_MAX_GLOWS];\n"
    "uniform vec4  u_glow_color[EDGE_LIGHT_MAX_GLOWS];\n"
    "uniform vec4  u_glow_additive;\n"
    "\n"
    "\n"
    "uniform float u_alpha;\n"
    "uniform float u_alpha_test;\n"
    "uniform float u_additive_pass;\n"
    "\n"
    "uniform float u_fog_mode;\n"
    "uniform vec4  u_fog_color;\n"
    "uniform float u_fog_density;\n"
    "uniform float u_fog_start;\n"
    "uniform float u_fog_end;\n"
    "\n"
    "uniform float u_oit_mode;\n"
    "uniform float u_oit_scale;\n"
    "\n"
    "varying vec4 v_color_and_u;\n"
    "varying vec4 v_eye_and_v;\n"
    "varying vec3 v_normal;\n"
    "\n"
    "const float kLightTileSize = 16.0;\n"
    "\n"
    "vec4 LightDataTexel(float index, float row)\n"
    "{\n"
    "    return texture2D(u_light_data, vec2((index + 0.5) * u_light_data_step, (row + 0.5) * 0.25));\n"
    "}\n"
    "\n"
    "void AccumulateTileLights(vec3 surface_position, vec3 surface_normal, float use_normal, inout vec3 modulate_sum,\n"
    "                          inout vec3 additive_sum)\n"
    "{\n"
    "    float tile_x = floor((gl_FragCoord.x - u_light_view.x) / kLightTileSize);\n"
    "    float tile_y = floor((gl_FragCoord.y - u_light_view.y) / kLightTileSize);\n"
    "\n"
    "    if (tile_x < 0.0 || tile_y < 0.0)\n"
    "        return;\n"
    "\n"
    "    vec4 header = texture2D(u_light_headers, vec2((tile_x + 0.5) * u_light_view.z, (tile_y + 0.5) * u_light_view.w));\n"
    "\n"
    "    float count = floor(header.a * 255.0 + 0.5);\n"
    "\n"
    "    if (count < 0.5)\n"
    "        return;\n"
    "\n"
    "    float offset = floor(header.r * 255.0 + 0.5) * 65536.0 + floor(header.g * 255.0 + 0.5) * 256.0 +\n"
    "                   floor(header.b * 255.0 + 0.5);\n"
    "\n"
    "    for (int slot = 0; slot < EDGE_LIGHT_MAX_PER_TILE; slot++)\n"
    "    {\n"
    "        if (float(slot) >= count)\n"
    "            break;\n"
    "\n"
    "        float entry = offset + float(slot);\n"
    "\n"
    "        float entry_y = floor(entry * u_light_list.y);\n"
    "        float entry_x = entry - entry_y * u_light_list.x;\n"
    "\n"
    "        float index = floor(\n"
    "            texture2D(u_light_indices, vec2((entry_x + 0.5) * u_light_list.y, (entry_y + 0.5) * u_light_list.z)).r *\n"
    "                255.0 +\n"
    "            0.5);\n"
    "\n"
    "        vec4 t0 = LightDataTexel(index, 0.0);\n"
    "        vec4 t1 = LightDataTexel(index, 1.0);\n"
    "\n"
    "        vec3 light_position;\n"
    "\n"
    "        light_position.x = u_light_bounds_min.x + (t0.r + t0.g / 255.0) * u_light_bounds_range.x;\n"
    "        light_position.y = u_light_bounds_min.y + (t0.b + t0.a / 255.0) * u_light_bounds_range.y;\n"
    "        light_position.z = u_light_bounds_min.z + (t1.r + t1.g / 255.0) * u_light_bounds_range.z;\n"
    "\n"
    "        float radius = (t1.b + t1.a / 255.0) * u_light_radius_scale;\n"
    "\n"
    "        vec3 delta = light_position - surface_position;\n"
    "\n"
    "        float normalised = dot(delta, delta) / (radius * radius);\n"
    "\n"
    "        if (normalised >= 1.0)\n"
    "            continue;\n"
    "\n"
    "        vec4 t2 = LightDataTexel(index, 2.0);\n"
    "\n"
    "        float shade = 1.0;\n"
    "\n"
    "        if (use_normal > 0.5)\n"
    "        {\n"
    "            shade = max(0.6 - 0.7 * dot(normalize(-delta), surface_normal), 0.0);\n"
    "        }\n"
    "\n"
    "        vec3 contribution = t2.rgb * exp(-5.44 * normalised) * shade;\n"
    "\n"
    "        if (t2.a > 0.5)\n"
    "            additive_sum += contribution;\n"
    "        else\n"
    "            modulate_sum += contribution;\n"
    "    }\n"
    "}\n"
    "\n"
    "void AccumulateGlows(vec3 surface_position, inout vec3 modulate_sum, inout vec3 additive_sum)\n"
    "{\n"
    "    for (int index = 0; index < EDGE_LIGHT_MAX_GLOWS; index++)\n"
    "    {\n"
    "        if (float(index) >= u_glow_count)\n"
    "            break;\n"
    "\n"
    "        float plane_distance = dot(vec4(surface_position, 1.0), u_glow_plane[index]);\n"
    "\n"
    "        float radius = u_glow_color[index].a;\n"
    "\n"
    "        float normalised = (plane_distance * plane_distance) / (radius * radius);\n"
    "\n"
    "        if (normalised >= 1.0)\n"
    "            continue;\n"
    "\n"
    "        vec3 contribution = u_glow_color[index].rgb * exp(-5.44 * normalised);\n"
    "\n"
    "        if (u_glow_additive[index] > 0.5)\n"
    "            additive_sum += contribution;\n"
    "        else\n"
    "            modulate_sum += contribution;\n"
    "    }\n"
    "}\n"
    "\n"
    "\n"
    "float FogFactor()\n"
    "{\n"
    "    if (u_fog_mode <= 0.5)\n"
    "    {\n"
    "        return 0.0;\n"
    "    }\n"
    "\n"
    "    float fog_distance = length(v_eye_and_v.xyz);\n"
    "\n"
    "    if (u_fog_mode < kFogLinear + 0.5)\n"
    "    {\n"
    "        return clamp(smoothstep(u_fog_start, u_fog_end, fog_distance), 0.0, 1.0);\n"
    "    }\n"
    "\n"
    "    return 1.0 - clamp(exp2(-u_fog_density * u_fog_density * fog_distance * fog_distance * kLog2), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "float OitWeight(float alpha, float view_depth)\n"
    "{\n"
    "    float a = min(1.0, alpha * 10.0) + 0.01;\n"
    "    float d = 1.0 - view_depth * 0.9;\n"
    "\n"
    "    return clamp(a * a * a * 1e8 * d * d * d, 1e-2, 3e3);\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 texel = texture2D(u_texture0, vec2(v_color_and_u.w, v_eye_and_v.w));\n"
    "\n"
    "    if (u_alpha_test > 0.0 && texel.a < u_alpha_test)\n"
    "    {\n"
    "        discard;\n"
    "    }\n"
    "\n"
    "    vec3 modulate_sum = vec3(0.0, 0.0, 0.0);\n"
    "    vec3 additive_sum = vec3(0.0, 0.0, 0.0);\n"
    "\n"
    "    if (u_world_lit > 0.5)\n"
    "    {\n"
    "        AccumulateTileLights(v_eye_and_v.xyz, normalize(v_normal), 1.0, modulate_sum, additive_sum);\n"
    "    }\n"
    "\n"
    "    if (u_glow_count > 0.5)\n"
    "    {\n"
    "        AccumulateGlows(v_eye_and_v.xyz, modulate_sum, additive_sum);\n"
    "    }\n"
    "\n"
    "    vec3 rgb = mix(texel.rgb * v_color_and_u.rgb, v_color_and_u.rgb, u_additive_pass);\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    if (fog_factor > 0.0)\n"
    "    {\n"
    "        rgb = mix(rgb, u_fog_color.rgb, fog_factor);\n"
    "    }\n"
    "\n"
    "    rgb += texel.rgb * modulate_sum + additive_sum;\n"
    "\n"
    "    vec4 fragment_color = vec4(rgb, texel.a * u_alpha);\n"
    "\n"
    "    if (u_oit_mode > 0.5)\n"
    "    {\n"
    "        float view_depth = clamp(-v_eye_and_v.z * 0.000625, 0.0, 1.0);\n"
    "\n"
    "        float weight = OitWeight(fragment_color.a, view_depth) * u_oit_scale;\n"
    "\n"
    "        if (u_oit_mode > 1.5)\n"
    "        {\n"
    "            gl_FragColor = vec4(fragment_color.a, 0.0, 0.0, fragment_color.a);\n"
    "            return;\n"
    "        }\n"
    "\n"
    "        gl_FragColor = vec4(fragment_color.rgb * fragment_color.a, fragment_color.a) * weight;\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    gl_FragColor = fragment_color;\n"
    "}\n"
    ;

