#pragma once

static const char kModelVertexSource[] =
    "uniform mat4 u_model_view_projection;\n"
    "uniform mat4 u_model_view;\n"
    "uniform mat4 u_model_transform;\n"
    "\n"
    "uniform float u_lerp;\n"
    "\n"
    "uniform vec2 u_texture_scale;\n"
    "uniform vec2 u_texture_offset;\n"
    "\n"
    "attribute vec3 a_position_frame1;\n"
    "attribute vec3 a_position_frame2;\n"
    "attribute vec2 a_texture_coordinates;\n"
    "attribute vec3 a_color;\n"
    "\n"
    "varying vec2 v_texture_coordinates;\n"
    "varying vec3 v_color;\n"
    "varying vec3 v_eye_position;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec3 blended = mix(a_position_frame1, a_position_frame2, u_lerp);\n"
    "\n"
    "    vec4 model_position = u_model_transform * vec4(blended, 1.0);\n"
    "\n"
    "    v_texture_coordinates = a_texture_coordinates * u_texture_scale + u_texture_offset;\n"
    "    v_color               = a_color;\n"
    "    v_eye_position        = (u_model_view * model_position).xyz;\n"
    "\n"
    "    gl_Position = u_model_view_projection * model_position;\n"
    "}\n"
    ;

static const char kModelFragmentSource[] =
    "const float kFogLinear = 1.0;\n"
    "const float kLog2      = 1.442695;\n"
    "\n"
    "uniform sampler2D u_texture0;\n"
    "\n"
    "uniform vec4 u_clip_plane[6];\n"
    "\n"
    "uniform float u_alpha;\n"
    "uniform float u_alpha_test;\n"
    "uniform float u_additive_pass;\n"
    "\n"
    "uniform float u_fog_mode;\n"
    "uniform vec4  u_fog_color;\n"
    "uniform float u_fog_density;\n"
    "uniform float u_fog_start;\n"
    "uniform float u_fog_end;\n"
    "\n"
    "varying vec2 v_texture_coordinates;\n"
    "varying vec3 v_color;\n"
    "varying vec3 v_eye_position;\n"
    "\n"
    "float FogFactor()\n"
    "{\n"
    "    if (u_fog_mode <= 0.5)\n"
    "    {\n"
    "        return 0.0;\n"
    "    }\n"
    "\n"
    "    float fog_distance = length(v_eye_position);\n"
    "\n"
    "    if (u_fog_mode < kFogLinear + 0.5)\n"
    "    {\n"
    "        return clamp(smoothstep(u_fog_start, u_fog_end, fog_distance), 0.0, 1.0);\n"
    "    }\n"
    "\n"
    "    return 1.0 - clamp(exp2(-u_fog_density * u_fog_density * fog_distance * fog_distance * kLog2), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 eye_position = vec4(v_eye_position, 1.0);\n"
    "\n"
    "    float clip_distance = 0.0;\n"
    "\n"
    "    for (int i = 0; i < 6; i++)\n"
    "    {\n"
    "        clip_distance += min(0.0, dot(eye_position, u_clip_plane[i]));\n"
    "    }\n"
    "\n"
    "    if (clip_distance < 0.0)\n"
    "    {\n"
    "        discard;\n"
    "    }\n"
    "\n"
    "    vec4 texel = texture2D(u_texture0, v_texture_coordinates);\n"
    "\n"
    "    if (u_alpha_test > 0.0 && texel.a < u_alpha_test)\n"
    "    {\n"
    "        discard;\n"
    "    }\n"
    "\n"
    "    vec3 rgb = mix(texel.rgb * v_color, v_color, u_additive_pass);\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    if (fog_factor > 0.0)\n"
    "    {\n"
    "        rgb = mix(rgb, u_fog_color.rgb, fog_factor);\n"
    "    }\n"
    "\n"
    "    gl_FragColor = vec4(rgb, texel.a * u_alpha);\n"
    "}\n"
    ;

