#pragma once

static const char kWorldVertexSource[] =
    "uniform mat4 u_model_view_projection;\n"
    "uniform mat4 u_model_view;\n"
    "\n"
    "uniform float u_sky_pass;\n"
    "uniform float u_sky_fog_depth;\n"
    "uniform float u_sky_geometry;\n"
    "\n"
    "uniform float u_light_depth;\n"
    "uniform vec4  u_view_tint;\n"
    "\n"
    "attribute vec3 a_position;\n"
    "attribute vec4 a_texture_coordinates;\n"
    "\n"
    "uniform vec2 u_texture_offset;\n"
    "attribute vec4 a_color;\n"
    "\n"
    "varying vec4 v_texture_coordinates;\n"
    "varying vec4 v_color;\n"
    "varying vec3 v_eye_position;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 model_position = vec4(a_position, 1.0);\n"
    "\n"
    "    v_texture_coordinates = a_texture_coordinates;\n"
    "    v_texture_coordinates.xy += u_texture_offset;\n"
    "    v_color               = a_color;\n"
    "    v_color.rgb *= u_view_tint.rgb;\n"
    "\n"
    "    if (u_sky_pass > 0.5)\n"
    "    {\n"
    "        v_eye_position = vec3(0.0, 0.0, -u_sky_fog_depth);\n"
    "\n"
    "        if (u_sky_geometry > 0.5)\n"
    "            gl_Position = u_model_view_projection * model_position;\n"
    "        else\n"
    "            gl_Position = vec4(a_position.xy, 1.0, 1.0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        v_eye_position = (u_model_view * model_position).xyz;\n"
    "\n"
    "        if (u_light_depth > 0.5)\n"
    "        {\n"
    "            v_texture_coordinates.z = -v_eye_position.z * 0.000625;\n"
    "        }\n"
    "\n"
    "        gl_Position = u_model_view_projection * model_position;\n"
    "    }\n"
    "}\n"
    ;

static const char kWorldFragmentSource[] =
    "const float kFogLinear = 1.0;\n"
    "const float kLog2      = 1.442695;\n"
    "\n"
    "uniform sampler2D u_texture0;\n"
    "uniform sampler2D u_texture1;\n"
    "uniform sampler2D u_color_lookup;\n"
    "uniform float     u_color_lookup_enabled;\n"
    "uniform float     u_whiten;\n"
    "uniform vec4      u_blur;\n"
    "uniform vec4      u_liquid;\n"
    "\n"
    "\n"
    "uniform float u_multi_texture;\n"
    "uniform float u_light_falloff;\n"
    "\n"
    "uniform sampler2D u_light_data;\n"
    "uniform sampler2D u_light_headers;\n"
    "uniform sampler2D u_light_indices;\n"
    "\n"
    "uniform float u_world_lit;\n"
    "uniform vec4  u_light_view;\n"
    "uniform vec4  u_light_list;\n"
    "\n"
    "uniform float u_glow_count;\n"
    "uniform vec4  u_glow_plane[EDGE_LIGHT_MAX_GLOWS];\n"
    "uniform vec4  u_glow_color[EDGE_LIGHT_MAX_GLOWS];\n"
    "uniform vec4  u_glow_additive;\n"
    "uniform vec3  u_light_bounds_min;\n"
    "uniform vec3  u_light_bounds_range;\n"
    "uniform float u_light_radius_scale;\n"
    "uniform float u_light_data_step;\n"
    "uniform float u_line_mode;\n"
    "uniform float u_skip_rgb;\n"
    "uniform float u_alpha_test;\n"
    "\n"
    "uniform float u_fog_mode;\n"
    "uniform vec4  u_fog_color;\n"
    "uniform float u_fog_density;\n"
    "uniform float u_fog_start;\n"
    "uniform float u_fog_end;\n"
    "\n"
    "uniform float u_sky_pass;\n"
    "uniform mat4  u_sky_inverse_projection;\n"
    "uniform mat4  u_sky_inverse_view;\n"
    "uniform vec4  u_sky_viewport;\n"
    "uniform float u_sky_stretch_mode;\n"
    "uniform float u_sky_u_scale;\n"
    "uniform float u_sky_ty;\n"
    "uniform float u_sky_u_offset;\n"
    "uniform float u_sky_v_offset;\n"
    "uniform float u_sky_vertical_fov_slope;\n"
    "uniform float u_sky_horizon_shift;\n"
    "uniform float u_sky_is_box;\n"
    "\n"
    "uniform float u_oit_mode;\n"
    "uniform float u_oit_scale;\n"
    "\n"
    "uniform samplerCube u_sky_cube;\n"
    "\n"
    "varying vec4 v_texture_coordinates;\n"
    "varying vec4 v_color;\n"
    "varying vec3 v_eye_position;\n"
    "\n"
    "const float kSkyStretchMirror  = 0.0;\n"
    "const float kSkyStretchRepeat  = 1.0;\n"
    "const float kSkyStretchStretch = 2.0;\n"
    "const float kSkyStretchVanilla = 3.0;\n"
    "\n"
    "const int   kSkyPinchTaps      = 64;\n"
    "const float kSkyPinchTapWeight = 0.015625;\n"
    "const float kSkyPinchFadeStart = 0.9397;\n"
    "const float kSkyPinchFadeEnd   = 0.9848;\n"
    "\n"
    "float FogFactor()\n"
    "{\n"
    "    if (u_fog_mode <= 0.5)\n"
    "    {\n"
    "        return 0.0;\n"
    "    }\n"
    "\n"
    "    float fog_distance = length(v_eye_position);\n"
    "\n"
    "    if (u_fog_mode < kFogLinear + 0.5)\n"
    "    {\n"
    "        return clamp(smoothstep(u_fog_start, u_fog_end, fog_distance), 0.0, 1.0);\n"
    "    }\n"
    "\n"
    "    return 1.0 - clamp(exp2(-u_fog_density * u_fog_density * fog_distance * fog_distance * kLog2), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "vec3 SkyDirection()\n"
    "{\n"
    "    vec2 ndc  = ((gl_FragCoord.xy - u_sky_viewport.xy) / u_sky_viewport.zw) * 2.0 - 1.0;\n"
    "    vec4 clip = vec4(ndc, 1.0, 1.0);\n"
    "    vec4 eye  = u_sky_inverse_projection * clip;\n"
    "    eye       = vec4(eye.xy, -1.0, 0.0);\n"
    "    return normalize((u_sky_inverse_view * eye).xyz);\n"
    "}\n"
    "\n"
    "vec4 SampleCubeSky()\n"
    "{\n"
    "    vec3 dir = SkyDirection();\n"
    "\n"
    "    vec4 sampled = textureCube(u_sky_cube, vec3(dir.y, -dir.z, dir.x));\n"
    "\n"
    "    vec3 rgb = sampled.rgb * v_color.rgb;\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    if (fog_factor > 0.0)\n"
    "    {\n"
    "        rgb = mix(rgb, u_fog_color.rgb, fog_factor);\n"
    "    }\n"
    "\n"
    "    return vec4(rgb, sampled.a * v_color.a);\n"
    "}\n"
    "\n"
    "vec4 SampleEquirectSky()\n"
    "{\n"
    "    vec3 dir = SkyDirection();\n"
    "\n"
    "    const float kTwoPi = 6.28318530718;\n"
    "\n"
    "    float horiz_len = max(length(dir.xy), 0.0001);\n"
    "    float sky_tan   = dir.z / horiz_len - u_sky_horizon_shift;\n"
    "    float p         = sky_tan / sqrt(1.0 + sky_tan * sky_tan);\n"
    "    float u = fract((atan(dir.y, dir.x) / kTwoPi + 0.5) * u_sky_u_scale + u_sky_u_offset);\n"
    "\n"
    "    bool mode_is_vanilla = abs(u_sky_stretch_mode - kSkyStretchVanilla) < 0.5;\n"
    "    bool mode_is_mirror  = abs(u_sky_stretch_mode - kSkyStretchMirror) < 0.5;\n"
    "    bool lower_hemisphere = p < 0.0;\n"
    "\n"
    "    float v_raw;\n"
    "\n"
    "    if (mode_is_vanilla)\n"
    "    {\n"
    "        float pc = clamp(sky_tan / u_sky_vertical_fov_slope, -1.0, 1.0);\n"
    "        v_raw           = (pc + 1.0) * 0.5 * u_sky_ty - u_sky_v_offset;\n"
    "    }\n"
    "    else if (mode_is_mirror)\n"
    "    {\n"
    "        float base = (p + 1.0) * 0.5 * u_sky_ty;\n"
    "        v_raw      = lower_hemisphere ? -(base + u_sky_v_offset) : (base - u_sky_v_offset);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        v_raw = (p + 1.0) * 0.5 * u_sky_ty - u_sky_v_offset;\n"
    "    }\n"
    "\n"
    "    float v = fract(v_raw);\n"
    "\n"
    "    vec4 sampled = texture2D(u_texture0, vec2(u, v));\n"
    "\n"
    "    float pinch_mix = smoothstep(kSkyPinchFadeStart, kSkyPinchFadeEnd, abs(dir.z));\n"
    "\n"
    "    if (pinch_mix > 0.0)\n"
    "    {\n"
    "        vec4 averaged = vec4(0.0);\n"
    "\n"
    "        float average_span = min(abs(u_sky_u_scale), 1.0);\n"
    "\n"
    "        for (int i = 0; i < kSkyPinchTaps; i++)\n"
    "        {\n"
    "            float tap = (float(i) + 0.5) * kSkyPinchTapWeight - 0.5;\n"
    "\n"
    "            averaged += texture2D(u_texture0, vec2(fract(u + tap * average_span), v));\n"
    "        }\n"
    "\n"
    "        sampled = mix(sampled, averaged * kSkyPinchTapWeight, pinch_mix);\n"
    "    }\n"
    "\n"
    "    vec3 rgb = sampled.rgb * v_color.rgb;\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    if (fog_factor > 0.0)\n"
    "    {\n"
    "        rgb = mix(rgb, u_fog_color.rgb, fog_factor);\n"
    "    }\n"
    "\n"
    "    return vec4(rgb, sampled.a * v_color.a);\n"
    "}\n"
    "\n"
    "const float kLightTileSize = 16.0;\n"
    "\n"
    "vec4 LightDataTexel(float index, float row)\n"
    "{\n"
    "    return texture2D(u_light_data, vec2((index + 0.5) * u_light_data_step, (row + 0.5) * 0.25));\n"
    "}\n"
    "\n"
    "void AccumulateTileLights(vec3 surface_position, vec3 surface_normal, float use_normal, inout vec3 modulate_sum,\n"
    "                          inout vec3 additive_sum)\n"
    "{\n"
    "    float tile_x = floor((gl_FragCoord.x - u_light_view.x) / kLightTileSize);\n"
    "    float tile_y = floor((gl_FragCoord.y - u_light_view.y) / kLightTileSize);\n"
    "\n"
    "    if (tile_x < 0.0 || tile_y < 0.0)\n"
    "        return;\n"
    "\n"
    "    vec4 header = texture2D(u_light_headers, vec2((tile_x + 0.5) * u_light_view.z, (tile_y + 0.5) * u_light_view.w));\n"
    "\n"
    "    float count = floor(header.a * 255.0 + 0.5);\n"
    "\n"
    "    if (count < 0.5)\n"
    "        return;\n"
    "\n"
    "    float offset = floor(header.r * 255.0 + 0.5) * 65536.0 + floor(header.g * 255.0 + 0.5) * 256.0 +\n"
    "                   floor(header.b * 255.0 + 0.5);\n"
    "\n"
    "    for (int slot = 0; slot < EDGE_LIGHT_MAX_PER_TILE; slot++)\n"
    "    {\n"
    "        if (float(slot) >= count)\n"
    "            break;\n"
    "\n"
    "        float entry = offset + float(slot);\n"
    "\n"
    "        float entry_y = floor(entry * u_light_list.y);\n"
    "        float entry_x = entry - entry_y * u_light_list.x;\n"
    "\n"
    "        float index = floor(\n"
    "            texture2D(u_light_indices, vec2((entry_x + 0.5) * u_light_list.y, (entry_y + 0.5) * u_light_list.z)).r *\n"
    "                255.0 +\n"
    "            0.5);\n"
    "\n"
    "        vec4 t0 = LightDataTexel(index, 0.0);\n"
    "        vec4 t1 = LightDataTexel(index, 1.0);\n"
    "\n"
    "        vec3 light_position;\n"
    "\n"
    "        light_position.x = u_light_bounds_min.x + (t0.r + t0.g / 255.0) * u_light_bounds_range.x;\n"
    "        light_position.y = u_light_bounds_min.y + (t0.b + t0.a / 255.0) * u_light_bounds_range.y;\n"
    "        light_position.z = u_light_bounds_min.z + (t1.r + t1.g / 255.0) * u_light_bounds_range.z;\n"
    "\n"
    "        float radius = (t1.b + t1.a / 255.0) * u_light_radius_scale;\n"
    "\n"
    "        vec3 delta = light_position - surface_position;\n"
    "\n"
    "        float normalised = dot(delta, delta) / (radius * radius);\n"
    "\n"
    "        if (normalised >= 1.0)\n"
    "            continue;\n"
    "\n"
    "        vec4 t2 = LightDataTexel(index, 2.0);\n"
    "\n"
    "        float shade = 1.0;\n"
    "\n"
    "        if (use_normal > 0.5)\n"
    "        {\n"
    "            shade = max(0.6 - 0.7 * dot(normalize(-delta), surface_normal), 0.0);\n"
    "        }\n"
    "\n"
    "        vec3 contribution = t2.rgb * exp(-5.44 * normalised) * shade;\n"
    "\n"
    "        if (t2.a > 0.5)\n"
    "            additive_sum += contribution;\n"
    "        else\n"
    "            modulate_sum += contribution;\n"
    "    }\n"
    "}\n"
    "\n"
    "void AccumulateGlows(vec3 surface_position, inout vec3 modulate_sum, inout vec3 additive_sum)\n"
    "{\n"
    "    for (int index = 0; index < EDGE_LIGHT_MAX_GLOWS; index++)\n"
    "    {\n"
    "        if (float(index) >= u_glow_count)\n"
    "            break;\n"
    "\n"
    "        float plane_distance = dot(vec4(surface_position, 1.0), u_glow_plane[index]);\n"
    "\n"
    "        float radius = u_glow_color[index].a;\n"
    "\n"
    "        float normalised = (plane_distance * plane_distance) / (radius * radius);\n"
    "\n"
    "        if (normalised >= 1.0)\n"
    "            continue;\n"
    "\n"
    "        vec3 contribution = u_glow_color[index].rgb * exp(-5.44 * normalised);\n"
    "\n"
    "        if (u_glow_additive[index] > 0.5)\n"
    "            additive_sum += contribution;\n"
    "        else\n"
    "            modulate_sum += contribution;\n"
    "    }\n"
    "}\n"
    "\n"
    "\n"
    "float OitWeight(float alpha, float view_depth)\n"
    "{\n"
    "    float a = min(1.0, alpha * 10.0) + 0.01;\n"
    "    float d = 1.0 - view_depth * 0.9;\n"
    "\n"
    "    return clamp(a * a * a * 1e8 * d * d * d, 1e-2, 3e3);\n"
    "}\n"
    "\n"
    "vec2 LiquidFlow(vec2 point, vec2 direction, float time, float seed)\n"
    "{\n"
    "    float k = 6.2831853 / 72.0;\n"
    "    vec2  q = point + direction * 6.0 * time;\n"
    "\n"
    "    q += 4.0 * vec2(sin(q.y * k + time * 0.9 + seed), sin(q.x * k * 1.13 - time * 0.7 + seed * 1.7));\n"
    "    q += 2.4 * vec2(sin((q.x + q.y) * k * 0.61 + time * 0.53 + seed * 2.3),\n"
    "                    sin((q.x - q.y) * k * 0.79 - time * 0.61 + seed * 0.4));\n"
    "\n"
    "    return q;\n"
    "}\n"
    "\n"
    "vec4 SampleLiquid(vec2 coordinate)\n"
    "{\n"
    "    vec2  size  = u_liquid.zw;\n"
    "    vec2  point = coordinate * size;\n"
    "    float time  = u_liquid.y;\n"
    "\n"
    "    if (u_liquid.x < 1.5)\n"
    "    {\n"
    "        float k     = 6.2831853 / 40.0;\n"
    "        float swirl = time * 2.0;\n"
    "\n"
    "        point += vec2(sin(point.y * k + swirl * 1.7) + sin(point.x * k * 0.5 + swirl * 1.1 + 1.3),\n"
    "                      sin(point.x * k + swirl * 1.3 + 0.7) + sin(point.y * k * 0.5 - swirl * 0.9 + 2.1));\n"
    "\n"
    "        float kt = 6.2831853 / 320.0;\n"
    "\n"
    "        point += 3.0 * vec2(sin((point.x + point.y) * kt + swirl * 0.8),\n"
    "                            sin((point.y - point.x) * kt * 1.21 + swirl * 0.6));\n"
    "\n"
    "        return texture2D(u_texture0, point / size);\n"
    "    }\n"
    "\n"
    "    if (u_liquid.x < 2.5)\n"
    "    {\n"
    "        vec4 lower = texture2D(u_texture0, LiquidFlow(point, vec2(0.8, 0.6), time, 0.0) / size);\n"
    "        vec4 upper = texture2D(u_texture0, LiquidFlow(point + 25.0, vec2(-0.97386, 0.22717), time * 1.3, 3.1) / size);\n"
    "\n"
    "        return mix(lower, upper, 0.33);\n"
    "    }\n"
    "\n"
    "    float row = floor(point.y) + 0.5;\n"
    "\n"
    "    point.x += 2.0 * sin(row * 6.2831853 / 16.0 + time * 4.0);\n"
    "\n"
    "    return texture2D(u_texture0, point / size);\n"
    "}\n"
    "\n"
    "vec4 SampleBlurred(vec2 coordinate)\n"
    "{\n"
    "    vec2  size  = u_blur.zw;\n"
    "    vec2  point = coordinate * size - 0.5;\n"
    "    vec2  base  = floor(point);\n"
    "    float scale = -0.5 / (u_blur.x * u_blur.x);\n"
    "    vec4  sum   = vec4(0.0);\n"
    "    float total = 0.0;\n"
    "\n"
    "    for (int j = -1; j <= 2; j++)\n"
    "    {\n"
    "        for (int i = -1; i <= 2; i++)\n"
    "        {\n"
    "            vec2  center = base + vec2(float(i), float(j));\n"
    "            vec2  delta  = center - point;\n"
    "            float weight = exp(dot(delta, delta) * scale);\n"
    "\n"
    "            sum += texture2D(u_texture0, (center + 0.5) / size) * weight;\n"
    "            total += weight;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    return sum / total;\n"
    "}\n"
    "\n"
    "vec3 WhitenColor(vec3 source)\n"
    "{\n"
    "    float brightest = max(source.r, max(source.g, source.b));\n"
    "\n"
    "    return vec3((brightest * 196.0 + (source.r + source.g + source.b) * 20.0) / 256.0);\n"
    "}\n"
    "\n"
    "vec3 ApplyColorLookup(vec3 source)\n"
    "{\n"
    "    vec3  scaled = clamp(source, 0.0, 1.0) * 63.0;\n"
    "    float blue0  = floor(scaled.b);\n"
    "    float blue1  = min(blue0 + 1.0, 63.0);\n"
    "    vec2  inner  = (scaled.rg + 0.5) / 512.0;\n"
    "    vec2  tile0  = vec2(mod(blue0, 8.0), floor(blue0 / 8.0)) * 0.125;\n"
    "    vec2  tile1  = vec2(mod(blue1, 8.0), floor(blue1 / 8.0)) * 0.125;\n"
    "    vec3  low    = texture2D(u_color_lookup, tile0 + inner).rgb;\n"
    "    vec3  high   = texture2D(u_color_lookup, tile1 + inner).rgb;\n"
    "\n"
    "    return mix(low, high, scaled.b - blue0);\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    if (u_sky_pass > 0.5)\n"
    "    {\n"
    "        if (u_sky_is_box > 0.5)\n"
    "            gl_FragColor = SampleCubeSky();\n"
    "        else\n"
    "            gl_FragColor = SampleEquirectSky();\n"
    "\n"
    "        if (u_color_lookup_enabled > 0.5)\n"
    "            gl_FragColor.rgb = ApplyColorLookup(gl_FragColor.rgb);\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    if (u_line_mode > 0.5)\n"
    "    {\n"
    "        float u           = v_texture_coordinates.x;\n"
    "        float v           = v_texture_coordinates.y;\n"
    "        float line_width  = v_texture_coordinates.z;\n"
    "        float line_length = v_texture_coordinates.w;\n"
    "        float aa_radius   = 1.0;\n"
    "\n"
    "        float au = 1.0 - smoothstep(1.0 - ((3.0 * aa_radius) / line_width), 1.0, abs(u / line_width));\n"
    "        float av = 1.0 - smoothstep(1.0 - ((3.0 * aa_radius) / line_length), 1.0, abs(v / line_length));\n"
    "\n"
    "        gl_FragColor = vec4(v_color.rgb, v_color.a * min(au, av));\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    vec4 texel0;\n"
    "\n"
    "    if (u_blur.x > 0.0)\n"
    "        texel0 = SampleBlurred(v_texture_coordinates.xy);\n"
    "    else if (u_liquid.x > 0.5)\n"
    "        texel0 = SampleLiquid(v_texture_coordinates.xy);\n"
    "    else\n"
    "        texel0 = texture2D(u_texture0, v_texture_coordinates.xy);\n"
    "\n"
    "\n"
    "    if (u_alpha_test > 0.0 && texel0.a < u_alpha_test)\n"
    "    {\n"
    "        discard;\n"
    "    }\n"
    "\n"
    "    if (u_color_lookup_enabled > 0.5)\n"
    "    {\n"
    "        texel0.rgb = ApplyColorLookup(texel0.rgb);\n"
    "    }\n"
    "\n"
    "    if (u_whiten > 0.5)\n"
    "    {\n"
    "        texel0.rgb = WhitenColor(texel0.rgb);\n"
    "    }\n"
    "\n"
    "    texel0 = mix(texel0, vec4(1.0, 1.0, 1.0, texel0.a), u_skip_rgb);\n"
    "\n"
    "    vec4 fragment_color = v_color;\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    vec3 modulate_sum = vec3(0.0, 0.0, 0.0);\n"
    "    vec3 additive_sum = vec3(0.0, 0.0, 0.0);\n"
    "\n"
    "    if (u_world_lit > 0.5)\n"
    "    {\n"
    "        AccumulateTileLights(v_eye_position, vec3(0.0, 0.0, 1.0), 0.0, modulate_sum, additive_sum);\n"
    "    }\n"
    "\n"
    "    if (u_glow_count > 0.5)\n"
    "    {\n"
    "        AccumulateGlows(v_eye_position, modulate_sum, additive_sum);\n"
    "    }\n"
    "\n"
    "    if (u_multi_texture > 0.5 || u_light_falloff > 0.5)\n"
    "    {\n"
    "        fragment_color *= texel0;\n"
    "\n"
    "        if (u_light_falloff > 0.5)\n"
    "        {\n"
    "            vec2 falloff = v_texture_coordinates.zw * 2.0 - 1.0;\n"
    "\n"
    "            fragment_color.rgb *= exp(-5.44 * dot(falloff, falloff));\n"
    "        }\n"
    "        else\n"
    "        {\n"
    "            fragment_color *= texture2D(u_texture1, v_texture_coordinates.zw);\n"
    "        }\n"
    "\n"
    "        if (fog_factor > 0.0)\n"
    "        {\n"
    "            fragment_color = mix(fragment_color, u_fog_color, fog_factor);\n"
    "        }\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        fragment_color *= texel0;\n"
    "\n"
    "        if (fog_factor > 0.0)\n"
    "        {\n"
    "            fragment_color.rgb = mix(fragment_color, u_fog_color, fog_factor).rgb;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    fragment_color.rgb += texel0.rgb * modulate_sum + additive_sum;\n"
    "\n"
    "    if (u_oit_mode > 0.5)\n"
    "    {\n"
    "        float view_depth = clamp(-v_eye_position.z * 0.000625, 0.0, 1.0);\n"
    "\n"
    "        float weight = OitWeight(fragment_color.a, view_depth) * u_oit_scale;\n"
    "\n"
    "        if (u_oit_mode > 1.5)\n"
    "        {\n"
    "            gl_FragColor = vec4(fragment_color.a, 0.0, 0.0, fragment_color.a);\n"
    "            return;\n"
    "        }\n"
    "\n"
    "        gl_FragColor = vec4(fragment_color.rgb * fragment_color.a, fragment_color.a) * weight;\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    gl_FragColor = fragment_color;\n"
    "}\n"
    ;

