#pragma once

static const char kWorldVertexSource[] =
    "uniform mat4 u_model_view_projection;\n"
    "uniform mat4 u_model_view;\n"
    "\n"
    "uniform float u_sky_pass;\n"
    "uniform float u_sky_fog_depth;\n"
    "\n"
    "attribute vec3 a_position;\n"
    "attribute vec4 a_texture_coordinates;\n"
    "attribute vec4 a_color;\n"
    "\n"
    "varying vec4 v_texture_coordinates;\n"
    "varying vec4 v_color;\n"
    "varying vec3 v_eye_position;\n"
    "\n"
    "void main()\n"
    "{\n"
    "    vec4 model_position = vec4(a_position, 1.0);\n"
    "\n"
    "    v_texture_coordinates = a_texture_coordinates;\n"
    "    v_color               = a_color;\n"
    "\n"
    "    if (u_sky_pass > 0.5)\n"
    "    {\n"
    "        v_eye_position = vec3(0.0, 0.0, -u_sky_fog_depth);\n"
    "\n"
    "        gl_Position = vec4(a_position.xy, 1.0, 1.0);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        v_eye_position = (u_model_view * model_position).xyz;\n"
    "\n"
    "        gl_Position = u_model_view_projection * model_position;\n"
    "    }\n"
    "}\n"
    ;

static const char kWorldFragmentSource[] =
    "const float kFogLinear = 1.0;\n"
    "const float kLog2      = 1.442695;\n"
    "\n"
    "uniform sampler2D u_texture0;\n"
    "uniform sampler2D u_texture1;\n"
    "\n"
    "uniform vec4 u_clip_plane[6];\n"
    "\n"
    "uniform float u_multi_texture;\n"
    "uniform float u_line_mode;\n"
    "uniform float u_skip_rgb;\n"
    "uniform float u_alpha_test;\n"
    "\n"
    "uniform float u_fog_mode;\n"
    "uniform vec4  u_fog_color;\n"
    "uniform float u_fog_density;\n"
    "uniform float u_fog_start;\n"
    "uniform float u_fog_end;\n"
    "\n"
    "uniform float u_sky_pass;\n"
    "uniform mat4  u_sky_inverse_projection;\n"
    "uniform mat4  u_sky_inverse_view;\n"
    "uniform vec4  u_sky_viewport;\n"
    "uniform float u_sky_stretch_mode;\n"
    "uniform float u_sky_u_scale;\n"
    "uniform float u_sky_ty;\n"
    "uniform float u_sky_u_offset;\n"
    "uniform float u_sky_v_offset;\n"
    "uniform float u_sky_vertical_fov_slope;\n"
    "uniform float u_sky_horizon_shift;\n"
    "\n"
    "varying vec4 v_texture_coordinates;\n"
    "varying vec4 v_color;\n"
    "varying vec3 v_eye_position;\n"
    "\n"
    "const float kSkyStretchMirror  = 0.0;\n"
    "const float kSkyStretchRepeat  = 1.0;\n"
    "const float kSkyStretchStretch = 2.0;\n"
    "const float kSkyStretchVanilla = 3.0;\n"
    "\n"
    "float FogFactor()\n"
    "{\n"
    "    if (u_fog_mode <= 0.5)\n"
    "    {\n"
    "        return 0.0;\n"
    "    }\n"
    "\n"
    "    float fog_distance = length(v_eye_position);\n"
    "\n"
    "    if (u_fog_mode < kFogLinear + 0.5)\n"
    "    {\n"
    "        return clamp(smoothstep(u_fog_start, u_fog_end, fog_distance), 0.0, 1.0);\n"
    "    }\n"
    "\n"
    "    return 1.0 - clamp(exp2(-u_fog_density * u_fog_density * fog_distance * fog_distance * kLog2), 0.0, 1.0);\n"
    "}\n"
    "\n"
    "vec4 SampleEquirectSky()\n"
    "{\n"
    "    vec2 ndc  = ((gl_FragCoord.xy - u_sky_viewport.xy) / u_sky_viewport.zw) * 2.0 - 1.0;\n"
    "    vec4 clip = vec4(ndc, 1.0, 1.0);\n"
    "    vec4 eye  = u_sky_inverse_projection * clip;\n"
    "    eye       = vec4(eye.xy, -1.0, 0.0);\n"
    "    vec3 dir  = normalize((u_sky_inverse_view * eye).xyz);\n"
    "\n"
    "    const float kTwoPi = 6.28318530718;\n"
    "\n"
    "    float horiz_len = max(length(dir.xy), 0.0001);\n"
    "    float sky_tan   = dir.z / horiz_len - u_sky_horizon_shift;\n"
    "    float p         = sky_tan / sqrt(1.0 + sky_tan * sky_tan);\n"
    "    float u = fract((atan(dir.y, dir.x) / kTwoPi + 0.5) * u_sky_u_scale + u_sky_u_offset);\n"
    "\n"
    "    bool mode_is_vanilla = abs(u_sky_stretch_mode - kSkyStretchVanilla) < 0.5;\n"
    "    bool mode_is_mirror  = abs(u_sky_stretch_mode - kSkyStretchMirror) < 0.5;\n"
    "    bool lower_hemisphere = p < 0.0;\n"
    "\n"
    "    float v_raw;\n"
    "\n"
    "    if (mode_is_vanilla)\n"
    "    {\n"
    "        float pc = clamp(sky_tan / u_sky_vertical_fov_slope, -1.0, 1.0);\n"
    "        v_raw           = (pc + 1.0) * 0.5 * u_sky_ty - u_sky_v_offset;\n"
    "    }\n"
    "    else if (mode_is_mirror)\n"
    "    {\n"
    "        float base = (p + 1.0) * 0.5 * u_sky_ty;\n"
    "        v_raw      = lower_hemisphere ? -(base + u_sky_v_offset) : (base - u_sky_v_offset);\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        v_raw = (p + 1.0) * 0.5 * u_sky_ty - u_sky_v_offset;\n"
    "    }\n"
    "\n"
    "    float v = fract(v_raw);\n"
    "\n"
    "    vec4 sampled = texture2D(u_texture0, vec2(u, v));\n"
    "\n"
    "    vec3 rgb = sampled.rgb * v_color.rgb;\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    if (fog_factor > 0.0)\n"
    "    {\n"
    "        rgb = mix(rgb, u_fog_color.rgb, fog_factor);\n"
    "    }\n"
    "\n"
    "    return vec4(rgb, sampled.a * v_color.a);\n"
    "}\n"
    "\n"
    "void main()\n"
    "{\n"
    "    if (u_sky_pass > 0.5)\n"
    "    {\n"
    "        gl_FragColor = SampleEquirectSky();\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    vec4 eye_position = vec4(v_eye_position, 1.0);\n"
    "\n"
    "    float clip_distance = 0.0;\n"
    "\n"
    "    for (int i = 0; i < 6; i++)\n"
    "    {\n"
    "        clip_distance += min(0.0, dot(eye_position, u_clip_plane[i]));\n"
    "    }\n"
    "\n"
    "    if (clip_distance < 0.0)\n"
    "    {\n"
    "        discard;\n"
    "    }\n"
    "\n"
    "    if (u_line_mode > 0.5)\n"
    "    {\n"
    "        float u           = v_texture_coordinates.x;\n"
    "        float v           = v_texture_coordinates.y;\n"
    "        float line_width  = v_texture_coordinates.z;\n"
    "        float line_length = v_texture_coordinates.w;\n"
    "        float aa_radius   = 1.0;\n"
    "\n"
    "        float au = 1.0 - smoothstep(1.0 - ((3.0 * aa_radius) / line_width), 1.0, abs(u / line_width));\n"
    "        float av = 1.0 - smoothstep(1.0 - ((3.0 * aa_radius) / line_length), 1.0, abs(v / line_length));\n"
    "\n"
    "        gl_FragColor = vec4(v_color.rgb, v_color.a * min(au, av));\n"
    "        return;\n"
    "    }\n"
    "\n"
    "    vec4 texel0 = texture2D(u_texture0, v_texture_coordinates.xy);\n"
    "\n"
    "    if (u_alpha_test > 0.0 && texel0.a < u_alpha_test)\n"
    "    {\n"
    "        discard;\n"
    "    }\n"
    "\n"
    "    texel0 = mix(texel0, vec4(1.0, 1.0, 1.0, texel0.a), u_skip_rgb);\n"
    "\n"
    "    vec4 fragment_color = v_color;\n"
    "\n"
    "    float fog_factor = FogFactor();\n"
    "\n"
    "    if (u_multi_texture > 0.5)\n"
    "    {\n"
    "        fragment_color *= texel0;\n"
    "        fragment_color *= texture2D(u_texture1, v_texture_coordinates.zw);\n"
    "\n"
    "        if (fog_factor > 0.0)\n"
    "        {\n"
    "            fragment_color = mix(fragment_color, u_fog_color, fog_factor);\n"
    "        }\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "        fragment_color *= texel0;\n"
    "\n"
    "        if (fog_factor > 0.0)\n"
    "        {\n"
    "            fragment_color.rgb = mix(fragment_color, u_fog_color, fog_factor).rgb;\n"
    "        }\n"
    "    }\n"
    "\n"
    "    gl_FragColor = fragment_color;\n"
    "}\n"
    ;

